### ISSUE TITLE
Game Design Question, Levels 13-18

### ISSUE THREAD

**Issue by NBumgardner** [MajorGrits/QuickSight#5]
# Overview
Within [the game](http://quicksight.azurewebsites.net/#/game/animals), a change of image layout occurs at Level 16, yet it uses the same number of images as before. Why replace the square-shaped pattern used in Levels 1-15?
## Comparisons Between Level Groupings
Levels 13-15 and 16-18 each use 49 images, yet they form two different shapes. 

Levels 1-15 form square-shaped grids from 3x3 to 7x7 images large.

Levels 16-18 form almost-rectangular grids. They are ((8x6)+1) images large, with the lowest image centered below the others.
## Design Question
Was Level 16 supposed to have more images than Level 15? If it were to continue the pattern in Levels 1-15, then Levels 16-18 would have an 8x8 grid. As it stands, Levels 13-15 and Levels 16-18 have the same number of images, just rearranged.

Although these last three levels slightly change the layout, they do not greatly increase difficulty as the previous levels did.
## Possible Solution
Since you give players 64 images to choose from, you could combine every available image to form an 8x8 grid to finish the last three levels of the game.

**Comment by MajorGrits** [comment]
The problem was the randomImageSet wasn't being properly loaded by the $rootScope.images. Fixed the loading process and also changed the beginBtn to hide properly after you started the game.
